source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '6.0'

pod 'AFNetworking', '~> 2.4'

# SVWebViewController 2014/10/08
pod 'SVWebViewController', :git => 'https://github.com/TransitApp/SVWebViewController', :commit => '5be38e427d'

